executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch 
    --job-name=smk-{rule}-{wildcards}
    --mail-user=hblee@umich.edu 
    --mail-type=BEGIN,END 
    --partition={resources.partition} 
    --account={resources.account} 
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-.%j.err
    --nodes={resources.nodes} 
    --cpus-per-task={resources.num_threads}
    --mem={resources.mem}
    --time={resources.time_limit}
default-resources: 
  - partition=standard
  - account=jonth0
  - nodes=1 
  - mem=5g 
  - num_threads=4 
  - time_limit="01-00:00:01"
jobs: 500
use-conda: True 
latency-wait: 60
printshellcmds: True
